name: libui build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: install dependencies
      run: python -m pip install --upgrade pip setuptools wheel
    - name: install meson
      run: python -m pip install meson
    - name: install ninja
      run: brew install ninja
    - name: install crystal
      run: brew install crystal
    - name: clone libui repository
      run: git clone https://github.com/andlabs/libui.git
    - name: setup the build
      run: cd ./libui && meson setup build
    - name: build and install libui
      run: cd ./libui && ninja -C build install
    - name: clone iu repository
      run: git clone https://github.com/grkek/iu.git
    - name: compile an example
      run: cd ./iu && crystal run example/hello_world.cr
    
      
